questions = [
    "I enjoy being the center of attention.",
    "I feel drained after socializing.",
    "I prefer one-on-one conversations to group ones.",
    "I often start conversations.",
    "I enjoy attending large events or parties.",
    "I focus more on ideas than facts.",
    "I enjoy thinking about abstract theories.",
    "I trust experience over theory.",
    "I like dealing with real-world issues, not hypotheticals.",
    "I pay close attention to details.",
    "I make decisions based on how I feel.",
    "I consider people’s feelings before making decisions.",
    "I value empathy over logic.",
    "I prefer fairness over rules.",
    "I dislike conflict and try to keep peace.",
    "I like having a daily routine.",
    "I work best with detailed plans.",
    "I prefer spontaneity over schedules.",
    "I get frustrated with disorganization.",
    "I’m flexible with last-minute changes.",
]